[application]

[web.app]

# HTML title tag content
title = "MD-Reader"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.bakaleme.md-reader"
publisher = "bakalemeHQ"

[bundle.linux]
targets = ["appimage"]